//--------------------------------
// © Ada Maynek 2024
// This software is released under the MIT License.
//--------------------------------
import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import { GoogleAnalytics } from "@next/third-parties/google";
import AnimatePage from '@/components/elements/animate-page'
import Header from "@/components/layouts/header"
import Footer from "@/components/layouts/footer"

const notoSansJP = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ada's Works",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const gaId = process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID;

  return (
    <html lang="ja" className="h-full">
      <body className={"h-full bg-gray-200 " + notoSansJP.className} >
        <div
          className={`
            flex flex-col min-h-screen h-full
            sm:mx-auto sm:w-4/5 sm:max-w-2xl
          `}
        >
          <header className="p-2 bg-white border-b">
            <Header />
          </header>
          <main className="flex-1 p-2 bg-white">
            <AnimatePage>
              {children}
            </AnimatePage>
          </main>
          <footer className="p-2 bg-gray-400 text-white">
            <Footer />
          </footer>
        </div>
        {gaId && <GoogleAnalytics gaId={gaId} />}
      </body>
    </html>
  );
}
